version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
      time: "23:00"
      timezone: "Pacific/Auckland"
    target-branch: "main"
    open-pull-requests-limit: 100
