name: Add Project from Issue

on:
  issues:
    types: [opened]
  schedule:
    - cron: '0 23 * * *'  # 每周日午夜运行

jobs:
  add-project:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub

      - name: Parse issue and update .gitmodules
        id: update_gitmodules
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          REPO_OWNER: adminlove520
          REPO_NAME: securitytools
        run: |
          python .github/scripts/update_gitmodules.py
        if: github.event_name == 'issues'

      - name: Check if submodule already exists
        if: ${{ steps.update_gitmodules.outcome == 'failure' }}
        run: |
          echo "Submodule already exists. Skipping further steps."
          exit 0

      - name: Add submodule
        if: ${{ steps.update_gitmodules.outcome != 'failure' }}
        run: |
          git submodule add "$PROJECT_LINK" "$LOCATION"


      - name: Add .gitkeep files
        run: |
          python .github/scripts/add_gitkeep.py
        if: github.event_name == 'schedule' || github.event_name == 'issues' || ${{ steps.update_gitmodules.outcome != 'failure' }}

      - name: Commit changes
        run: |
          git config user.name ProjectBot
          git config user.email projectbotma@yourdomain.com
          git add .gitmodules
          git add projects/
          rm -rf projects/scanning/vulns/nuclei-templates
          git submodule update --init --recursive
          git add -A
          git commit -m "Cleanup 404 repositories, update files, and add .gitkeep"
          git push origin main
        if: github.event_name == 'schedule' || github.event_name == 'issues' || ${{ steps.update_gitmodules.outcome != 'failure' }}

      - name: Debug .gitmodules content
        run: |
          cat .gitmodules | grep "nuclei-templates"
        if: github.event_name == 'issues' || ${{ steps.update_gitmodules.outcome != 'failure' }}