name: Add Project from Issue

on:
  issues:
    types: [opened]
  schedule:
    - cron: '0 23 * * *'  # 每周日午夜运行

jobs:
  add-project:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write  # 已有写权限，支持关闭 Issue

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub

      - name: Parse issue and update .gitmodules
        id: parse_issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          REPO_OWNER: adminlove520
          REPO_NAME: securitytools
        run: |
          python .github/scripts/update_gitmodules.py
        if: github.event_name == 'issues'

      - name: Cleanup 404 repositories & add submodule files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOCATION: ${{ steps.parse_issue.outputs.location }}
          PROJECT_LINK: ${{ steps.parse_issue.outputs.project_link }}
        run: |
          git submodule add "$PROJECT_LINK" "$LOCATION"
        if: github.event_name == 'schedule' || github.event_name == 'issues'

      - name: Add .gitkeep files
        run: |
          python .github/scripts/add_gitkeep.py
        if: github.event_name == 'schedule' || github.event_name == 'issues'

      - name: Commit changes
        run: |
          git config user.name ProjectBot
          git config user.email projectbot@yourdomain.com
          git add .gitmodules
          git add projects/
          git add -A
          git commit -m "Cleanup 404 repositories, update files, and add .gitkeep"
          git push origin main
        if: github.event_name == 'schedule' || github.event_name == 'issues'

      # 新增：关闭触发的 Issue（仅当由 Issue 触发时执行）
      - name: Close the issue
        uses: actions-ecosystem/action-close-issue@v1
        with:
          issue-number: ${{ github.event.issue.number }}  # 获取触发的 Issue 编号
          comment: "项目已成功添加，此 Issue 自动关闭。"
        if: github.event_name == 'issues'  # 仅 Issue 触发时关闭