name: Cleanup Repos

on:
  # 新的触发条件
  schedule:
    - cron: '0 */5 * * *'  # 每 5 小时触发一次
  issues:
    types: [opened]  # 有新 issue 提交时触发

jobs:
  cleanup:
    runs-on: windows-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2
        with:
          submodules: true  # 确保子模块被初始化和更新
        id: checkout_step  # 标记步骤 ID 用于后续条件判断
        continue-on-error: true  # 允许步骤失败但作业继续执行

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
        if: steps.checkout_step.outcome == 'failure'  # 仅当 checkout 失败时准备环境

      - name: Run cleanup script
        working-directory: ./
        run: python .\securitytools\.github\scripts\cleanup_repos.py
        if: steps.checkout_step.outcome == 'failure'  # 仅当 checkout 失败时执行清理