name: submodule json array generator
on:
  workflow_run:
    workflows: ["Add Project"]
    types:
      - completed
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  report-generator:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2
        #with: 
          #submodules: true
      - name: run report generator
        run: |
          python3 docs/directory-gen.py
        env: 
          GITHUB_TOKEN: ${{ github.token }}
      - name: save changes
        run: |
          git config user.name DirectoryBot
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git commit --all --message "directoryBot-directory.json is updated" || echo "no changes to commit"
          git push
